Hods 174 - Adding CT endpoints and domain models
hmrc/organisations-details-api pull request #39
Opened 2021-07-20 10:15 UTC by matthewharris1

2021-07-23 12:19 UTC, Luka-Abey requested changes
Just a couple comments about comments

2021-07-23 12:19 UTC, Luka-Abey commented on app/uk/gov/hmrc/organisationsdetailsapi/controllers/CorporationTaxController.scala
> +  // TODO: add me to the routes files
as far as I can see, this has been done? If so, please remove comment :)
```suggestion
```

2021-07-23 12:19 UTC, Luka-Abey commented on test/unit/uk/gov/hmrc/organisationsdetailsapi/audit/AuditHelperSpec.scala
> +  //TODO: Add test for auditing Corporation tax response
also here - looks like its been added to corpTaxControllerSpec
```suggestion
```

2021-07-26 07:31 UTC, ajchilts requested changes

2021-07-26 07:31 UTC, ajchilts commented on test/component/uk/gov/hmrc/organisationsdetailsapi/connectors/IfConnectorSpec.scala
>        "microservice.services.integration-framework.host" -> "localhost",
In order to comply with the latest auth upgrade please change the host to `127.0.0.1`. This means that it routes through auth correctly as localhost will bypass.

2021-07-26 07:31 UTC, ajchilts commented on test/component/uk/gov/hmrc/organisationsdetailsapi/stubs/BaseSpec.scala
> +      "microservice.services.integration-framework.host" -> "localhost",
In order to comply with the latest auth upgrade please change the host to 127.0.0.1. This means that it routes through auth correctly as localhost will bypass.

2021-07-26 08:32 UTC, owen-opencast requested changes

2021-07-26 13:29 UTC, owen-opencast requested changes
Looks good, just spotted we need the default port specifying in build.sbt (see orgs matching)

2021-07-26 13:47 UTC, owen-opencast approved these changes

2021-07-26 13:48 UTC, ajchilts approved these changes
Looking good now 👍

2021-07-26 14:24 UTC, merged