Hods 176 : Added number of employees endpoint and tests surrounding it.
hmrc/organisations-details-api pull request #44
Opened 2021-07-28 14:07 UTC by parkeradam

2021-07-28 15:19 UTC, Luka-Abey requested changes
just very minor style things - looks good :)

2021-07-28 15:19 UTC, Luka-Abey commented on conf/app_version_v1_0.routes
> +POST        /number-of-employees                    @uk.gov.hmrc.organisationsdetailsapi.controllers.NumberOfEmployeesController.numberOfEmployees(matchId: java.util.UUID)
```suggestion
POST       /number-of-employees                    @uk.gov.hmrc.organisationsdetailsapi.controllers.NumberOfEmployeesController.numberOfEmployees(matchId: java.util.UUID)
```

2021-07-28 15:22 UTC, Luka-Abey approved these changes

2021-07-29 11:57 UTC, ajchilts requested changes

2021-07-29 11:57 UTC, ajchilts commented on app/uk/gov/hmrc/organisationsdetailsapi/controllers/NumberOfEmployeesController.scala
> +            val response = Json.toJson(state(Json.obj("returns" -> numberOfEmployees)) ++ selfLink)
Should this be `returns`? Documentation shows counts. As this is already in the Json do we want this here?

2021-07-29 11:57 UTC, ajchilts commented on app/uk/gov/hmrc/organisationsdetailsapi/services/NumberOfEmployeesService.scala
> +            cacheId = CorporationTaxCacheId(matchId, cacheKey),
CorporationTaxCacheId? I think we need a new cache ID here as it needs to also include the date ranges past in. I.e. a request may be considered different with different date ranges.

2021-07-29 13:39 UTC, ajchilts approved these changes
LGTM. Well done 👍

2021-08-02 15:46 UTC, Luka-Abey approved these changes

2021-08-02 16:37 UTC, merged