HODS-433 | Implemented new mongo implementation
hmrc/organisations-details-api pull request #63
Opened 2021-09-28 09:04 UTC by matthewharris1

2021-09-28 15:23 UTC, parkeradam commented on test/unit/uk/gov/hmrc/organisationsdetailsapi/services/CacheServiceSpec.scala
> -    "return the cached value for a given id and key" in new Setup {
Is there a reason these tests are deleted? They seem like reasonably valuable tests?

2021-09-29 08:07 UTC, ajchilts requested changes

2021-09-29 08:07 UTC, ajchilts commented on app/uk/gov/hmrc/organisationsdetailsapi/cache/ShortLivedCache.scala
> +class ShortLivedCache @Inject() (val cacheConfig: CacheRepositoryConfiguration,
Why are we keeping this class when we have added the new cache repository?

2021-09-29 08:11 UTC, ajchilts requested changes

2021-09-29 08:11 UTC, ajchilts commented on test/it/uk/gov/hmrc/organisationsdetailsapi/cache/ShortLivedCacheSpec.scala
>  class ShortLivedCacheSpec
We have created a cache repository so we do not need this test class? Do we have one to cover cache repository?

2021-09-29 12:01 UTC, ajchilts approved these changes

2021-09-29 12:11 UTC, Luka-Abey requested changes

2021-09-29 12:11 UTC, Luka-Abey commented on app/uk/gov/hmrc/organisationsdetailsapi/cache/CacheRepository.scala
> +    .getOrElse("individuals-details-cache")
```suggestion
    .getOrElse("organisations-details-cache")
```

2021-09-29 12:24 UTC, parkeradam approved these changes

2021-09-29 12:25 UTC, Luka-Abey approved these changes

2021-09-29 13:39 UTC, merged